### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by tedbjurlin** [DiscoTrayStudios/WaterQualityTester#1]
**Is your feature request related to a problem? Please describe.**
The map provided by Google does not load. It is a blank screen.

**Describe the solution you'd like**
Investigate what is preventing the map from loading and fix it. Is it location permissions?

**Comment by reidst** [comment]
The reason the map didn't work (prior to removal from the app) was probably because an API key was removed from `android/app/src/main/AndroidManifest.xml`.
```xml
15 <!-- Google Maps API key -->
16 <meta-data android:name="com.google.android.geo.API_KEY"
17        android:value="ADD_API_KEY_HERE"/>
```

**Comment by tedbjurlin** [comment]
App fully removed now.
